version: '3.2'

services:
  app:
    container_name: "app"
    build: ./app/.
    ports:
      - "9090:9090"
    volumes:
      - /Users/bariseser/Desktop/devops/docker-volumes/app/log:/app/log
    networks:
      - elk-stack
  nginx:
    image: nginx:latest
    container_name: "nginx"
    volumes:
      - "./nginx/config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/config/nginx.conf:/etc/nginx/nginx.conf"
      - /Users/bariseser/Desktop/devops/docker-volumes/nginx/log:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - elk-stack
  elastic:
    image: elasticsearch:8.3.3
    container_name: "elastic"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - /Users/bariseser/Desktop/devops/docker-volumes/elastic/:/usr/share/elasticsearch/data
      - "./elastic/config/elasticsearch.yml://usr/share/elasticsearch/config/elasticsearch.yml"
    networks:
      - elk-stack
  kibana:
    image: kibana:8.3.3
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk-stack
    environment:
      - elasticsearch.hosts=http://elastic:9200
    depends_on:
      - elastic  
  filebeat:
    image: elastic/filebeat:8.3.3
    container_name: "filebeat"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /Users/bariseser/Desktop/devops/docker-volumes/nginx/log:/var/log/nginx
      - /Users/bariseser/Desktop/devops/docker-volumes/app/log:/var/log/app
    depends_on:
      - logstash
    networks:
      - elk-stack
    ports:
      - "5400:5400"
  logstash:
    image: logstash:8.3.3
    container_name: "logstash"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
    networks:
      - elk-stack
networks:
  elk-stack:
    driver: bridge