version: '3.2'

services:
  app:
    container_name: "app"
    build: ./app/.
    ports:
      - "9090:9090"
    volumes:
      - ./app/log:/app/log
    networks:
      - elk-stack
  filebeat:
    image: elastic/filebeat:8.3.3
    container_name: "filebeat"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./app/log:/var/log/app
    depends_on:
      - logstash
    networks:
      - elk-stack
    ports:
      - "5400:5400"
networks:
  elk-stack:
    driver: bridge