filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/app/app.log
  tags: ["go-access-log"]

filebeat.config.modules:
  enabled: true
  path: /usr/share/filebeat/modules.d/*.yml

#output.console:
#  pretty: true

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]